##Reality 4.2.1

Thank you for purchasing Reality 4. 

This document is an extract from the Reality User's Guide, which explains Reality 4 in detail. The Reality User's Guide is included with Reality and it's available from the Help menu.

This document containes the instructions on how to install Reality on your computer. In here you will find instruction for both the Poser and DAZ Studio Editions of Reality.

###InstallationReality runs on both OS X and Windows (32 and 64-bit versions). The installation is automated by the Reality installer and most of the times all you will have to do is to simply click on the Install button and everything will be done in a few seconds.

When you download Reality the program is distributed as a dmg file for Mac OS and as a self-extracting zip for Windows.

On Mac OS, double-clicking on the DMG file will mount it in the Finder and from there you can simply double-click on the installer.

On Windows, double-clicking on the executable will show a window to select the destination folder for expanding the archive. Select a folder and confirm the operation. The result will be a folder with the name starting with "Reality". Open that folder and from there double-click on the RealityInstaller program to start the installation.

**Poser and DAZ Studio must be closed before running the Reality Installer.**

###Important
Reality connectes to Poser or DAZ Studio using a TCP/IP, the same protocol used for Internet. It is therefore necessary that both Reality and the host--Poser or DAZ Studio--have unrestricted ability to create Internet connections. If a Firewall or Anti-Virus program blocks access to Internet Reality will not be able to work. 

If  you use any software that blocks incoming and outgoing connections then make sure that Reality, Poser and DAZ Studio have unrestricted Internet access.

### Installing Reality Poser Edition

**Important**

If you have Reality 3 installed on your computer you must delete it before installing Reality 4. Here is how to do it:

- Delete the Reality folder inside the Runtime/Python/addons folder of Poser
- Delete the Reality Props and Lights from your Poser runtime.
The Reality installer automatically searches the hard disk of the computer to locate the right version of Poser. The installer also verifies that the bitness of Reality matches the one of Poser. In case you have multiple version of Poser installed and the Reality installer selects the wrong one, you can change the selection by clicking on the Change button. Navigate to the folder when the desired version of Poser is installed and select that folder.

If you need to install Reality for multiple versions of Poser, for example for Poser 9 and Poser 10, you will need to repeat the installation for each version of Poser.

The installer provides some valuable information in the main screen. For the OS X version the program confirms that this is a Universal binary, which means that it works both on 32 and 64-bit versions of OS X. The second line from the top lists the full version number of the program.

###Matching the bitnessThe following only applies to Windows; the OS X version of Reality ships as a universal binary capable of running at both 32 and 64 bits.
With Windows it’s important that you select the installer that matches the bitness of Poser. Please note that this is not the bitness of your OS. For example, Poser 10 is a 32-bit program even if you install it on a 64-bit version of OS X or Windows. In addition, even the Pro version of Poser will run at 32 bits if the computer and the OS are running at 32 bits.
Every plugin must match the bitness of the host. If you use 32-bit Poser then you must install the 32-bit version of Reality. If you use a 64-bit Poser then you must install the 64-bit version of Reality.

You can easily verify what is the bitness of Poser by running the program and then looking at the title-bar of the Poser window. The 64-bit version of Poser prints the text *(64-bit)* in the title bar. Otherwise you have a 32-bit version of the program.
###Props and LightsReality Poser Edition includes the plugin itself, the Reality program, and a series of Props and Lights, which can be installed in any Runtime of your choice. The installer selects a suitable default location, but that can be changed to any folder of your liking. Regardless of what folder is selected, the Reality Installer will automatically update Poser’s configuration to include that Runtime, so that the Reality Props and Lights will appear in the Poser Library.

When everything is set as desired, simply click on the Install button and the installation will start. In a few seconds the process will be completed and you will be able to use Reality.

###Installing Reality DAZ Studio Edition

**Important**

If you have Reality 2 installed on your computer you can use Reality 2 and Reality 4 side by side but you need to change the name of the Reality 2 folder where the plugin is installed **before** you run the installation of Reality 4. 
Look in the **plugins** folder where Studio is installed and find the Reality folder. Rename it to Reality2 or anything else of your linking and you're done.
This needs to be done only once; if you re-install Reality 4 then you don't need to repeat this step.
The Reality installer automatically searches the hard disk of the computer to locate the right version of DAZ Studio. The installer also verifies that the bitness of Reality matches the one of DAZ Studio. In case you have multiple version of DAZ Studio installed, and the Reality installer selects the wrong one, you can change the selection by clicking on the Change button. Navigate to the folder when the desired version of DAZ Studio is installed and select that folder. Please note that if you select a version of DAZ Studio that does not match the bitness of Reality, the Install button will not become enabled.

The installer provides some valuable information in the main screen. The first line confirms what version you are installing and the second line provides the complete version number.
Reality is composed of a plugin, which runs as an extension of DAZ Studio, and the Reality program itself, which provides the User Interface with which you configure the rendering of your scene.The installer shows the locations for the plugin portion, the program portion and the props and light of Reality. The plugin portion must be installed where DAZ Studio is installed.
The program portion can be installed anywhere. The installer suggest a location that is appropriate for your system but you can change that directory.

The same is true for the Props and Lights. The installer selects a suitable default location for those but it that can be changed to any folder of your liking. Regardless of what folder is selected, the Reality Installer will automatically update DAZ Studio’s configuration to include that Runtime, so that the Reality Lights and Props will appear in the DAZ Studio Content Library.

Happy rendering!
